version: "3"
services: 
  node-app :
    build: .
    ports: 
      - "3000:3000"
    environment: 
      - PORT=3000
  postgres:
    image: postgres:13.3-alpine
    env_file: 
      - ./.env
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes: 
  pgdata: