version: "3"
services: 
  node-app :
    build: 
      context: .
      args: 
        NODE_ENV: production
    environment: 
      - NODE_ENV=production
    command: >
      /bin/sh -c "npm run build && npm run start"